name: Java CI

on:
  push:
    branches:
      - main
      - workflow
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: wozudemo


    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Start Mysql service
        run: systemctl start mariadb
      - name: Verify MySql
        run: mysql --port 3306 -u root -p password -e "SHOW DATABASES"
      - name: Build with Maven
        run: mvn -B package --file pom.xml



